# Generated by Django 5.2.17 on 2026-09-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqr',
            options={'ordering': ['created_at']},
        ),
    ]
