# Generated by Django 5.2.17 on 2026-09-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pqr_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqr',
            name='channel',
            field=models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('in_person', 'Presencial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pqr',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pqr',
            name='status',
            field=models.CharField(choices=[('received', 'Recibida'), ('in_progress', 'En gestión'), ('resolved', 'Resuelta'), ('closed', 'Cerrada')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='pqr',
            name='type',
            field=models.CharField(choices=[('petition', 'Petición'), ('complaint', 'Queja'), ('claim', 'Reclamo')], max_length=20),
        ),
    ]
