FROM python:3.10.11-alpine3.16

ENV PYTHONDONTWRITEBYTECODE=1 
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# RUN apt-get update && apt-get install -y \
#     gcc \
#     libpq-dev \
#     && rm -rf /var/lib/apt/lists/*


COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./


# CMD ["python3", "manage.py", "runserver", "0.0.0.0:800", "--noreload"]
# CMD ["sh", "entrypoint.sh"]

